from app.models import db, Comment
import datetime

def seed_comments():
    a = Comment(project_id=1, user_id=3,  message="You’re a great listener.")
    b = Comment(project_id=1, user_id=9,  message="If someone based an Internet meme on you, it would have impeccable grammar.")
    c = Comment(project_id=1, user_id=8,  message="You’re a gift to those around you.")
    d = Comment(project_id=1, user_id=2,  message="You're an awesome friend.")
    e = Comment(project_id=2, user_id=9,  message="You’re that “Nothing” when people ask me what I’m thinking about.")
    f = Comment(project_id=2, user_id=5,  message="You light up the room.")
    g = Comment(project_id=2, user_id=6,  message="Your kindness is a balm to all who encounter it.")
    h = Comment(project_id=2, user_id=1,  message="You seem to really know who you are.")
    i = Comment(project_id=3, user_id=8,  message="You're a gift to those around you.")
    g = Comment(project_id=3, user_id=5,  message="You're a great example to others.")
    k = Comment(project_id=3, user_id=1,  message="You're always learning new things and trying to better yourself, which is awesome.")
    l = Comment(project_id=4, user_id=1,  message="On a scale from 1 to 10, you’re an 11.")
    m = Comment(project_id=4, user_id=9,  message="The way you treasure your loved ones is incredible.")
    n = Comment(project_id=4, user_id=10, message="Thank you for being there for me.")
    o = Comment(project_id=5, user_id=2,  message="I like your style.")
    p = Comment(project_id=5, user_id=7,  message="You’re all that and a super-size bag of chips.")
    q = Comment(project_id=5, user_id=8,  message="You’re like sunshine on a rainy day.")
    r = Comment(project_id=5, user_id=9,  message="Jokes are funnier when you tell them.")
    s = Comment(project_id=5, user_id=6,  message="You're a candle in the darkness.")
    t = Comment(project_id=6, user_id=4,  message="You have impeccable manners.")
    u = Comment(project_id=6, user_id=8,  message="You’re strong.")
    v = Comment(project_id=6, user_id=10, message="You were cool way before hipsters were cool.")
    w = Comment(project_id=6, user_id=2,  message="You’re the coolest person I know. And I consider myself bet friends with like all celebrities, so. . . .")
    x = Comment(project_id=6, user_id=7,  message="On a scale from 1 to 10, you're an 11.")
    y = Comment(project_id=6, user_id=9,  message="You are really kind to people around you.")
    z = Comment(project_id=7, user_id=2,  message="You deserve a hug right now.")
    aa = Comment(project_id=7, user_id=5,  message="Jokes are funnier when you tell them.")
    bb = Comment(project_id=7, user_id=1,  message="Being around you is like being on a happy little vacation.")
    cc = Comment(project_id=7, user_id=9,  message="The way you treasure your loved ones is incredible.")
    dd = Comment(project_id=7, user_id=4,  message="You're more helpful than you realize.")
    ee = Comment(project_id=8, user_id=2,  message="You’re strong.")
    ff = Comment(project_id=8, user_id=5,  message="You have the courage of your convictions.")
    gg = Comment(project_id=8, user_id=9,  message="You’re inspiring.")
    hh = Comment(project_id=8, user_id=3,  message="You’re like a breath of fresh air.")
    ii = Comment(project_id=8, user_id=7,  message="You're more helpful than you realize.")
    jj = Comment(project_id=8, user_id=10,  message="If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer).")
    kk = Comment(project_id=8, user_id=1,  message="There's ordinary, and then there's you.")
    ll = Comment(project_id=9, user_id=1,  message="You’re that “Nothing” when people ask me what I’m thinking about.")
    mm = Comment(project_id=9, user_id=8,  message="Hanging out with you is always a blast.")
    nn = Comment(project_id=9, user_id=10,  message="You may dance like no one’s watching, but everyone’s watching because you’re an amazing dancer!")
    oo = Comment(project_id=9, user_id=5,  message="When you say, “I meant to do that,” I totally believe you.")
    pp = Comment(project_id=9, user_id=3,  message="There’s ordinary, and then there’s you.")
    qq = Comment(project_id=9, user_id=7,  message="You’re a gift to those around you.")
    rr = Comment(project_id=9, user_id=4,  message="You're a smart cookie.")
    ss = Comment(project_id=10, user_id=5,  message="You bring out the best in other people.")
    tt = Comment(project_id=10, user_id=8,  message="How is it that you always look great, even in sweatpants?")
    uu = Comment(project_id=10, user_id=9,  message="You’re wonderful.")
    vv = Comment(project_id=10, user_id=1,  message="You're great at figuring stuff out.")
    # f = Comment(project_id=, user_id=,  message="")

    db.session.add(a)
    db.session.add(b)
    db.session.add(c)
    db.session.add(d)
    db.session.add(e)
    db.session.add(f)
    db.session.add(g)
    db.session.add(h)
    db.session.add(i)
    db.session.add(k)
    db.session.add(l)
    db.session.add(m)
    db.session.add(n)
    db.session.add(o)
    db.session.add(p)
    db.session.add(q)
    db.session.add(r)
    db.session.add(s)
    db.session.add(t)
    db.session.add(u)
    db.session.add(v)
    db.session.add(w)
    db.session.add(x)
    db.session.add(y)
    db.session.add(z)
    db.session.add(aa)
    db.session.add(bb)
    db.session.add(cc)
    db.session.add(dd)
    db.session.add(ee)
    db.session.add(ff)
    db.session.add(gg)
    db.session.add(hh)
    db.session.add(ii)
    db.session.add(jj)
    db.session.add(kk)
    db.session.add(ll)
    db.session.add(mm)
    db.session.add(nn)
    db.session.add(oo)
    db.session.add(pp)
    db.session.add(qq)
    db.session.add(rr)
    db.session.add(ss)
    db.session.add(tt)
    db.session.add(uu)
    db.session.add(vv)

    db.session.commit()

def undo_comment():
    db.session.execute('TRUNCATE comments RESTART IDENTITY CASCADE;')
    db.session.commit()
