from app.models import db, Project
from datetime import datetime, timedelta

def seed_projects():
    oneP = Project(
        name='VGDLOVE!! - Visual novel dating sim',
        user_id=1,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed elementum tempus egestas sed sed risus. Et magnis dis parturient montes nascetur ridiculus mus. Massa placerat duis ultricies lacus sed. Arcu non sodales neque sodales ut. Nulla facilisi morbi tempus iaculis. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Ut tristique et egestas quis ipsum suspendisse. Ultricies integer quis auctor elit sed vulputate mi sit amet. Vitae proin sagittis nisl rhoncus mattis rhoncus urna neque viverra. Convallis convallis tellus id interdum velit laoreet id donec. Rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. A lacus vestibulum sed arcu non odio euismod lacinia. Nisl nisi scelerisque eu ultrices vitae auctor. Est velit egestas dui id ornare arcu odio ut sem. Sapien et ligula ullamcorper malesuada proin. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Aliquet bibendum enim facilisis gravida neque convallis a cras. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla. Ipsum dolor sit amet consectetur adipiscing.

Integer eget aliquet nibh praesent. Lorem donec massa sapien faucibus. Turpis egestas pretium aenean pharetra magna. Volutpat est velit egestas dui id ornare arcu odio. Diam sollicitudin tempor id eu nisl. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Nisl purus in mollis nunc sed id semper. In tellus integer feugiat scelerisque varius. Netus et malesuada fames ac turpis. Consequat id porta nibh venenatis cras sed felis eget. Sit amet luctus venenatis lectus magna fringilla. Commodo elit at imperdiet dui accumsan. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Nisl suscipit adipiscing bibendum est ultricies. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Massa sapien faucibus et molestie ac feugiat. Lacus luctus accumsan tortor posuere ac.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra adipiscing at in tellus. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Nec ultrices dui sapien eget mi proin sed. Habitant morbi tristique senectus et netus et. Velit euismod in pellentesque massa placerat duis ultricies lacus. Vel quam elementum pulvinar etiam non. Accumsan tortor posuere ac ut consequat semper viverra nam. At varius vel pharetra vel. Tempor id eu nisl nunc mi ipsum faucibus vitae. Sem integer vitae justo eget magna fermentum iaculis. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Sed turpis tincidunt id aliquet risus feugiat in ante. Purus sit amet volutpat consequat. Euismod quis viverra nibh cras pulvinar mattis nunc. Facilisi etiam dignissim diam quis. Varius sit amet mattis vulputate. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. At tempor commodo ullamcorper a lacus vestibulum sed arcu.""",
        created_at=datetime.today(),
        genres='Ren\'Py',
        image='https://img.itch.zone/aW1hZ2UvMjEyNzg5LzEwMDM5MDUucG5n/347x500/arD4E3.png')

    twoP = Project(
        name='Overcooked - Couch co-op cooking game',
        user_id=2,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id eu nisl nunc mi ipsum faucibus. Habitant morbi tristique senectus et netus et malesuada fames. Sit amet cursus sit amet. Tellus at urna condimentum mattis pellentesque id. Enim sed faucibus turpis in. Risus nullam eget felis eget nunc lobortis mattis. Quis risus sed vulputate odio ut. Ut tellus elementum sagittis vitae et leo duis ut. Eu lobortis elementum nibh tellus molestie nunc non blandit. Orci ac auctor augue mauris augue. Mattis aliquam faucibus purus in massa. Convallis a cras semper auctor neque vitae. Proin gravida hendrerit lectus a. Elit duis tristique sollicitudin nibh. Aliquet enim tortor at auctor urna nunc.

Ac feugiat sed lectus vestibulum mattis. Eget aliquet nibh praesent tristique magna sit amet. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Proin fermentum leo vel orci porta non pulvinar neque. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Congue eu consequat ac felis donec. Faucibus a pellentesque sit amet porttitor eget dolor. Velit scelerisque in dictum non consectetur a erat nam at. Sem fringilla ut morbi tincidunt. Mattis molestie a iaculis at erat. At augue eget arcu dictum varius duis at. Eu ultrices vitae auctor eu augue ut lectus arcu bibendum. Vitae congue eu consequat ac felis donec et odio. Massa eget egestas purus viverra accumsan in. Mollis nunc sed id semper risus in. Porttitor eget dolor morbi non arcu risus quis varius. Orci porta non pulvinar neque laoreet suspendisse. Tellus at urna condimentum mattis pellentesque id nibh tortor. Cursus turpis massa tincidunt dui.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus in metus vulputate eu scelerisque felis imperdiet. Vulputate mi sit amet mauris commodo quis imperdiet. Ultricies integer quis auctor elit sed vulputate mi sit. Nisl purus in mollis nunc sed id semper. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Blandit turpis cursus in hac habitasse. Non tellus orci ac auctor augue mauris augue neque. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum.""",
        created_at=datetime.today(),
        genres='Unity',
        image='https://cdn.cdkeys.com/500x706/media/catalog/product/o/v/overcooked-pc-get-cheap-cd-key_7_.jpg')

    threeP = Project(
        name='Jackbox - Local/online party game',
        user_id=3,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Magna sit amet purus gravida. Libero nunc consequat interdum varius sit amet. Tempus imperdiet nulla malesuada pellentesque elit. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Ipsum a arcu cursus vitae congue mauris. Ridiculus mus mauris vitae ultricies leo integer malesuada. Sit amet venenatis urna cursus eget. Mi proin sed libero enim sed. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Vitae tortor condimentum lacinia quis vel. Mi proin sed libero enim sed faucibus. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Tempus quam pellentesque nec nam.

Massa tincidunt nunc pulvinar sapien et. Mattis vulputate enim nulla aliquet porttitor lacus. Mauris vitae ultricies leo integer malesuada nunc vel. Magna eget est lorem ipsum dolor. Morbi quis commodo odio aenean. Ullamcorper a lacus vestibulum sed arcu. Purus viverra accumsan in nisl nisi scelerisque. Eget magna fermentum iaculis eu non diam phasellus. Ipsum dolor sit amet consectetur adipiscing. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Vitae congue mauris rhoncus aenean vel elit. Lorem ipsum dolor sit amet consectetur adipiscing. Urna id volutpat lacus laoreet non. Auctor augue mauris augue neque gravida in fermentum et. Bibendum ut tristique et egestas. A scelerisque purus semper eget duis at tellus at urna. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Non sodales neque sodales ut etiam sit. Et netus et malesuada fames ac turpis egestas.""",
        owner_description='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut sem nulla pharetra diam. Imperdiet proin fermentum leo vel orci porta. Sit amet aliquam id diam maecenas. Viverra adipiscing at in tellus integer feugiat scelerisque. Consequat interdum varius sit amet mattis. Faucibus turpis in eu mi bibendum neque egestas congue quisque. Diam quam nulla porttitor massa id neque. Pellentesque elit eget gravida cum sociis natoque penatibus et. Accumsan sit amet nulla facilisi morbi. Dignissim diam quis enim lobortis.',
        created_at=datetime.today(),
        genres='Other',
        image='https://external-preview.redd.it/fXM22-XxI8nF_1M261rCVYgV6rk5WBIY48EyT6Gu5FE.jpg?auto=webp&s=1db03b65aa2f2e22818a591518a28147b7abf40f')

    fourP = Project(
        name='Mystic Messenger - Storytelling messenger game',
        user_id=4,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Facilisi etiam dignissim diam quis enim. Tempus imperdiet nulla malesuada pellentesque elit eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl. Tristique sollicitudin nibh sit amet commodo nulla facilisi. Cursus sit amet dictum sit. Facilisis volutpat est velit egestas dui id ornare arcu. Volutpat consequat mauris nunc congue nisi. Quis viverra nibh cras pulvinar. Nam libero justo laoreet sit amet cursus sit amet. Lectus magna fringilla urna porttitor rhoncus dolor. Nisi vitae suscipit tellus mauris a diam maecenas sed. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Urna nunc id cursus metus aliquam eleifend mi in nulla. Commodo ullamcorper a lacus vestibulum.

Vel pretium lectus quam id leo in. Pellentesque elit eget gravida cum. Diam maecenas ultricies mi eget. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Tincidunt augue interdum velit euismod in pellentesque massa. Nam libero justo laoreet sit amet. Posuere urna nec tincidunt praesent semper. Mattis pellentesque id nibh tortor id aliquet. Adipiscing diam donec adipiscing tristique. Semper auctor neque vitae tempus quam pellentesque.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget velit aliquet sagittis id consectetur purus. Sollicitudin nibh sit amet commodo nulla facilisi. Diam donec adipiscing tristique risus nec feugiat in fermentum posuere. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Non curabitur gravida arcu ac tortor dignissim. Sapien eget mi proin sed libero enim. Odio tempor orci dapibus ultrices in iaculis nunc. Sed nisi lacus sed viverra tellus. Pellentesque pulvinar pellentesque habitant morbi tristique senectus. At risus viverra adipiscing at in tellus. Arcu bibendum at varius vel pharetra vel.""",
        created_at=datetime.today(),
        genres='Unity',
        image='https://media.pocketgamer.biz/2017/1/73240/mystic-messenger-icon-r225x.jpg')

    fiveP = Project(
        name='Sun Haven - Multiplayer fantasy farming sim',
        user_id=5,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Egestas maecenas pharetra convallis posuere morbi leo urna molestie. Fames ac turpis egestas maecenas. Eget nunc lobortis mattis aliquam faucibus purus in. Suspendisse interdum consectetur libero id. Feugiat vivamus at augue eget arcu dictum varius. Tortor pretium viverra suspendisse potenti nullam ac tortor vitae purus. Convallis tellus id interdum velit laoreet. Et ultrices neque ornare aenean. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Euismod nisi porta lorem mollis aliquam ut porttitor leo a.

Neque convallis a cras semper auctor. Amet purus gravida quis blandit turpis cursus in hac habitasse. Est ullamcorper eget nulla facilisi etiam. Pellentesque habitant morbi tristique senectus et netus et malesuada. Viverra nam libero justo laoreet sit amet cursus. Malesuada proin libero nunc consequat interdum. Ut eu sem integer vitae justo eget magna. Tellus molestie nunc non blandit massa enim. Vestibulum mattis ullamcorper velit sed. Nisi est sit amet facilisis magna etiam tempor orci. Neque sodales ut etiam sit amet nisl. Vivamus at augue eget arcu. Nunc id cursus metus aliquam eleifend mi. Molestie at elementum eu facilisis sed odio morbi quis commodo. Blandit volutpat maecenas volutpat blandit aliquam etiam erat.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Luctus accumsan tortor posuere ac ut. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Vel facilisis volutpat est velit egestas dui. Mi in nulla posuere sollicitudin aliquam. Dolor magna eget est lorem ipsum.""",
        created_at=datetime.today(),
        genres='Unity',
        image='https://i.ytimg.com/vi/LROTU2VnGHM/maxresdefault.jpg')

    sixP = Project(
        name='Beat Saber - Virtual reality rhythm game',
        user_id=6,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Sit amet nisl suscipit adipiscing. Tristique risus nec feugiat in. Consequat ac felis donec et odio. Adipiscing at in tellus integer feugiat scelerisque varius. Feugiat in ante metus dictum at tempor. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Pharetra convallis posuere morbi leo urna. Vulputate eu scelerisque felis imperdiet proin fermentum leo.

Cursus vitae congue mauris rhoncus. Massa id neque aliquam vestibulum morbi blandit cursus risus. Imperdiet proin fermentum leo vel orci porta non. Proin nibh nisl condimentum id venenatis a condimentum. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Purus non enim praesent elementum facilisis leo vel. Feugiat nibh sed pulvinar proin gravida hendrerit. Nascetur ridiculus mus mauris vitae ultricies leo. Orci nulla pellentesque dignissim enim sit amet. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Leo urna molestie at elementum eu facilisis.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa massa ultricies mi quis hendrerit dolor magna eget. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Velit egestas dui id ornare arcu odio ut. Faucibus turpis in eu mi bibendum. Aliquam sem et tortor consequat id porta nibh venenatis cras. Urna porttitor rhoncus dolor purus non. Laoreet id donec ultrices tincidunt arcu. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Luctus accumsan tortor posuere ac ut consequat semper. Varius quam quisque id diam. Nunc consequat interdum varius sit.""",
        created_at=datetime.today(),
        genres='Unity',
        image='https://image.api.playstation.com/cdn/UP4882/CUSA12878_00/NOTe9PbIoUkvKQU6VPceO4f9pGdazDv1.png')

    sevenP = Project(
        name='Valheim - Norse-themed survival sandbox',
        user_id=7,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Placerat in egestas erat imperdiet. Mattis enim ut tellus elementum sagittis vitae et leo. Erat pellentesque adipiscing commodo elit at. Nulla facilisi etiam dignissim diam quis enim. Tristique senectus et netus et malesuada fames. Sapien et ligula ullamcorper malesuada proin libero. Commodo nulla facilisi nullam vehicula. Ut porttitor leo a diam sollicitudin tempor. In ante metus dictum at tempor. Interdum varius sit amet mattis. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Dolor morbi non arcu risus quis varius quam quisque id. Rhoncus dolor purus non enim. Nec nam aliquam sem et. Faucibus turpis in eu mi. Ac turpis egestas sed tempus urna et. Tempus urna et pharetra pharetra massa massa ultricies mi. In nulla posuere sollicitudin aliquam ultrices sagittis.

Tortor consequat id porta nibh venenatis cras sed felis. Et pharetra pharetra massa massa ultricies mi quis. Cursus sit amet dictum sit. Tortor dignissim convallis aenean et tortor at. Mi quis hendrerit dolor magna eget. Non diam phasellus vestibulum lorem sed. Platea dictumst vestibulum rhoncus est pellentesque elit. Mattis ullamcorper velit sed ullamcorper morbi tincidunt. Purus sit amet volutpat consequat mauris nunc congue. Quis hendrerit dolor magna eget est lorem ipsum.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa massa ultricies mi quis hendrerit dolor magna eget. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Velit egestas dui id ornare arcu odio ut. Faucibus turpis in eu mi bibendum. Aliquam sem et tortor consequat id porta nibh venenatis cras. Urna porttitor rhoncus dolor purus non. Laoreet id donec ultrices tincidunt arcu. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Luctus accumsan tortor posuere ac ut consequat semper. Varius quam quisque id diam. Nunc consequat interdum varius sit.""",
        created_at=datetime.today(),
        genres='Unity',
        image='https://i.ytimg.com/vi/yMmCfcWHyfs/maxresdefault.jpg')

    eightP = Project(
        name='Inscryption - Horror deck-building game',
        user_id=8,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Feugiat pretium nibh ipsum consequat. Varius sit amet mattis vulputate enim. Malesuada proin libero nunc consequat interdum. Iaculis eu non diam phasellus vestibulum lorem sed risus. Viverra nam libero justo laoreet sit amet cursus. Pellentesque diam volutpat commodo sed egestas egestas. Egestas purus viverra accumsan in. Vulputate mi sit amet mauris commodo quis imperdiet massa. Fermentum posuere urna nec tincidunt. Ante metus dictum at tempor commodo ullamcorper a lacus. Eu scelerisque felis imperdiet proin fermentum leo vel orci. Adipiscing diam donec adipiscing tristique.

A erat nam at lectus urna duis. Tincidunt tortor aliquam nulla facilisi cras fermentum. Neque convallis a cras semper auctor. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Venenatis a condimentum vitae sapien pellentesque habitant. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Et ultrices neque ornare aenean euismod. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Scelerisque in dictum non consectetur a. Eu lobortis elementum nibh tellus molestie nunc non blandit.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor id eu nisl nunc. Nec dui nunc mattis enim ut tellus elementum sagittis. At erat pellentesque adipiscing commodo elit at imperdiet. Ut pharetra sit amet aliquam id diam. Morbi tempus iaculis urna id volutpat lacus laoreet non. Quis ipsum suspendisse ultrices gravida dictum fusce. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Lectus quam id leo in. Blandit aliquam etiam erat velit scelerisque in. Ut etiam sit amet nisl purus in. Nibh tortor id aliquet lectus proin nibh nisl. Sed velit dignissim sodales ut eu sem. Quisque id diam vel quam elementum pulvinar. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Eget arcu dictum varius duis at consectetur. Egestas diam in arcu cursus euismod.""",
        created_at=datetime.today(),
        genres='Unity',
        image="""https://www.gamespot.com/a/uploads/scale_landscape/1581/15811374/3901363-inscryptionkeyart.jpg""")

    nineP = Project(
        name='Amogus - Online multiplayer social deduction game',
        user_id=9,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At elementum eu facilisis sed odio morbi. Ornare suspendisse sed nisi lacus sed viverra tellus in. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Dui nunc mattis enim ut tellus elementum. Elementum tempus egestas sed sed. Mattis enim ut tellus elementum sagittis vitae. Morbi tristique senectus et netus et malesuada fames ac turpis. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Scelerisque in dictum non consectetur. Neque convallis a cras semper auctor neque vitae. Aliquam faucibus purus in massa tempor nec feugiat nisl pretium. Turpis egestas pretium aenean pharetra magna ac. Fusce ut placerat orci nulla pellentesque dignissim enim sit amet. Proin sed libero enim sed faucibus turpis in eu. Aliquet bibendum enim facilisis gravida neque convallis a. Phasellus vestibulum lorem sed risus. Tincidunt dui ut ornare lectus. Tellus id interdum velit laoreet id donec. Vitae aliquet nec ullamcorper sit amet risus nullam eget felis.

Ut sem viverra aliquet eget. Praesent semper feugiat nibh sed pulvinar. Dui ut ornare lectus sit amet est placerat in. Vestibulum mattis ullamcorper velit sed. Mattis aliquam faucibus purus in massa tempor nec feugiat. Sit amet volutpat consequat mauris nunc congue nisi. Euismod nisi porta lorem mollis aliquam ut. Lectus quam id leo in vitae turpis massa sed. Faucibus interdum posuere lorem ipsum dolor sit. Eu facilisis sed odio morbi quis commodo odio aenean sed. Faucibus in ornare quam viverra orci sagittis. Neque sodales ut etiam sit amet nisl purus in. Cursus vitae congue mauris rhoncus. Elementum pulvinar etiam non quam lacus suspendisse faucibus. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Fringilla ut morbi tincidunt augue interdum velit.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fringilla urna porttitor rhoncus dolor purus non. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Quam pellentesque nec nam aliquam sem. Nisi porta lorem mollis aliquam ut porttitor leo a. Penatibus et magnis dis parturient. Eu nisl nunc mi ipsum faucibus vitae aliquet. Morbi quis commodo odio aenean sed adipiscing. Massa id neque aliquam vestibulum morbi blandit cursus risus.""",
        created_at=datetime.today(),
        genres='Unity',
        image='https://play-lh.googleusercontent.com/8ddL1kuoNUB5vUvgDVjYY3_6HwQcrg1K2fd_R8soD-e2QYj8fT9cfhfh3G0hnSruLKec')

    tenP = Project(
        name='Stardew Valley - Simulation role-playing game',
        user_id=10,
        project_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Est velit egestas dui id ornare arcu odio. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Velit egestas dui id ornare. Hendrerit gravida rutrum quisque non tellus orci ac auctor augue. Dapibus ultrices in iaculis nunc. Libero nunc consequat interdum varius. In mollis nunc sed id semper. Donec pretium vulputate sapien nec sagittis. Turpis cursus in hac habitasse platea dictumst. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Id aliquet risus feugiat in ante. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Vitae justo eget magna fermentum iaculis eu. Nunc vel risus commodo viverra maecenas accumsan. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Diam ut venenatis tellus in metus vulputate. Suspendisse sed nisi lacus sed viverra. Cursus vitae congue mauris rhoncus aenean vel.

Leo a diam sollicitudin tempor id eu nisl nunc. Porttitor massa id neque aliquam vestibulum morbi blandit cursus risus. Aliquam sem fringilla ut morbi tincidunt. Nunc consequat interdum varius sit amet. Gravida neque convallis a cras. Fringilla phasellus faucibus scelerisque eleifend donec. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Massa massa ultricies mi quis hendrerit dolor magna eget. Amet consectetur adipiscing elit ut aliquam purus sit amet. Justo donec enim diam vulputate ut. Est placerat in egestas erat imperdiet sed euismod. Suscipit tellus mauris a diam maecenas sed enim ut. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Nunc eget lorem dolor sed viverra ipsum nunc. Etiam erat velit scelerisque in dictum non consectetur.""",
        owner_description="""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Feugiat vivamus at augue eget arcu dictum varius duis. Urna nunc id cursus metus aliquam eleifend mi in. Mi ipsum faucibus vitae aliquet nec. Diam in arcu cursus euismod quis viverra nibh cras. Nisl nisi scelerisque eu ultrices vitae. Risus nec feugiat in fermentum. Dignissim enim sit amet venenatis urna cursus eget. Mi eget mauris pharetra et. Sagittis orci a scelerisque purus semper eget. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Id volutpat lacus laoreet non. Mi sit amet mauris commodo quis. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Elit pellentesque habitant morbi tristique senectus et netus et. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Gravida rutrum quisque non tellus orci ac auctor augue.""",
        created_at=datetime.today(),
        genres='Other',
        image="""https://upload.wikimedia.org/wikipedia/en/f/fd/Logo_of_Stardew_Valley.png""")

    db.session.add(oneP)
    db.session.add(twoP)
    db.session.add(threeP)
    db.session.add(fourP)
    db.session.add(fiveP)
    db.session.add(sixP)
    db.session.add(sevenP)
    db.session.add(eightP)
    db.session.add(nineP)
    db.session.add(tenP)

    db.session.commit()

# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_projects():
    db.session.execute('TRUNCATE projects RESTART IDENTITY CASCADE;')
    db.session.commit()
