"""empty message

Revision ID: bf024f3ec97d
Revises: b2c462078989
Create Date: 2021-11-29 01:36:37.884414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf024f3ec97d'
down_revision = 'b2c462078989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deadline')
    op.drop_index('project_id_idx', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('project_id_idx', 'roles', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
