"""empty message

Revision ID: 55229375eed2
Revises: bf024f3ec97d
Create Date: 2021-11-29 10:09:47.613355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55229375eed2'
down_revision = 'bf024f3ec97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'image',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
